# Generated by Django 5.1.6 on 2025-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RectangularNotchReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho', models.FloatField(verbose_name='Datum Height (m)')),
                ('h', models.FloatField(verbose_name='Water Surface Elevation (m)')),
                ('volume', models.FloatField(verbose_name='Volume Collected (L)')),
                ('time', models.FloatField(verbose_name='Time (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
