# Generated by Django 5.1.6 on 2025-05-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0001_initial'),
    ]

    operations = [
    ]
