# Generated by Django 5.1.6 on 2025-05-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0002_auto_20250504_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rectangularnotchreading',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='rectangularnotchreading',
            old_name='volume',
            new_name='volume_liters',
        ),
    ]
