# Generated by Django 5.1.6 on 2025-05-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0003_alter_rectangularnotchreading_options_and_more'),
    ]

    operations = [
    ]
