# Generated by Django 5.1.6 on 2025-05-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0004_auto_20250504_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rectangularnotchreading',
            old_name='volume_liters',
            new_name='volume',
        ),
    ]
