# Generated by Django 5.1.4 on 2025-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rect', '0005_rename_volume_liters_rectangularnotchreading_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectangularnotchreading',
            name='h',
            field=models.FloatField(verbose_name='h (mm)'),
        ),
        migrations.AlterField(
            model_name='rectangularnotchreading',
            name='ho',
            field=models.FloatField(verbose_name='ho (mm)'),
        ),
    ]
